{
 "title": "xxx系统-接口监控",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "center",
    "label": "中心",
    "query": {
     "query": "label_values(entnglog_http_response_count_total{job=\"企业业务开发团队\", system=\"xxx系统\"}, idc)"
    }
   },
   {
    "name": "module",
    "label": "模块",
    "query": {
     "query": "label_values(entnglog_http_response_count_total{job=\"企业业务开发团队\", system=\"xxx系统\", idc=\"$center\"}, module)"
    }
   },
   {
    "name": "instance",
    "label": "实例",
    "query": {
     "query": "label_values(entnglog_http_response_count_total{job=\"企业业务开发团队\", system=\"xxx系统\", idc=\"$center\", module=\"$module\"}, upstream)"
    }
   },
   {
    "name": "service",
    "label": "服务",
    "query": {
     "query": "label_values(entnglog_http_response_count_total{job=\"企业业务开发团队\", system=\"xxx系统\", idc=\"$center\", module=\"$module\", upstream=~\"$instance\"}, request)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "总请求量",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(entnglog_http_upstream_time_seconds_count{job=\"企业业务开发团队\", system=\"xxx系统\", idc=\"$center\",module=\"$module\", upstream=~\"$instance\"}[10m]))",
     "legendFormat": "今日"
    },
    {
     "expr": "sum(increase(entnglog_http_upstream_time_seconds_count{job=\"企业业务开发团队\", system=\"xxx系统\", idc=\"$center\",module=\"$module\", upstream=~\"$instance\"}[10m] offset 1d))",
     "legendFormat": "昨日"
    },
    {
     "expr": "sum(increase(entnglog_http_upstream_time_seconds_count{job=\"企业业务开发团队\", system=\"xxx系统\", idc=\"$center\",module=\"$module\", upstream=~\"$instance\"}[10m] offset 7d))",
     "legendFormat": "上周"
    }
   ]
  },
  {
   "title": "总QPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(entnglog_http_upstream_time_seconds_count{job=\"企业业务开发团队\", system=\"xxx系统\", idc=\"$center\",module=\"$module\", upstream=~\"$instance\"}[10m]))",
     "legendFormat": "今日"
    },
    {
     "expr": "sum(rate(entnglog_http_upstream_time_seconds_count{job=\"企业业务开发团队\", system=\"xxx系统\", idc=\"$center\",module=\"$module\", upstream=~\"$instance\"}[10m] offset 1d))",
     "legendFormat": "昨日"
    },
    {
     "expr": "sum(rate(entnglog_http_upstream_time_seconds_count{job=\"企业业务开发团队\", system=\"xxx系统\", idc=\"$center\",module=\"$module\", upstream=~\"$instance\"}[10m] offset 7d))",
     "legendFormat": "上周"
    }
   ]
  },
  {
   "title": "整体P90",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(entnglog_http_upstream_time_seconds_hist_bucket{job=\"企业业务开发团队\", system=\"xxx系统\", idc=\"$center\",module=\"$module\", upstream=~\"$instance\"}[10m])) by (le))"
    }
   ]
  },
  {
   "title": "整体P99",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(entnglog_http_upstream_time_seconds_hist_bucket{job=\"企业业务开发团队\", system=\"xxx系统\", idc=\"$center\",module=\"$module\", upstream=~\"$instance\"}[10m])) by (le))"
    }
   ]
  },
  {
   "title": "请求耗时",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(entnglog_http_upstream_time_seconds_sum{job=\"企业业务开发团队\", system=\"xxx系统\", idc=\"$center\",module=\"$module\", upstream=~\"$instance\",request=~\".*$service.*\"}[10m])) by (request) / sum(rate(entnglog_http_upstream_time_seconds_count{job=\"企业业务开发团队\", system=\"xxx系统\", idc=\"$center\",module=\"$module\", upstream=~\"$instance\",request=~\".*$service.*\"}[10m])) by (request)",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "错误率",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(entnglog_http_upstream_time_seconds_count{job=\"企业业务开发团队\", system=\"xxx系统\", idc=\"$center\",module=\"$module\", upstream=~\"$instance\", request=~\".*$service.*\",status!~\"20\\\\d\"}[10m])) / sum(increase(entnglog_http_upstream_time_seconds_count{job=\"企业业务开发团队\", system=\"xxx系统\", idc=\"$center\",module=\"$module\", upstream=~\"$instance\",request=~\".*$service.*\"}[10m]))",
     "legendFormat": "今日"
    },
    {
     "expr": "sum(increase(entnglog_http_upstream_time_seconds_count{job=\"企业业务开发团队\", system=\"xxx系统\", idc=\"$center\",module=\"$module\", upstream=~\"$instance\", request=~\".*$service.*\",status!~\"20\\\\d\"}[10m] offset 1d)) / sum(increase(entnglog_http_upstream_time_seconds_count{job=\"企业业务开发团队\", system=\"xxx系统\", idc=\"$center\",module=\"$module\", upstream=~\"$instance\",request=~\".*$service.*\"}[10m] offset 1d))",
     "legendFormat": "昨日"
    },
    {
     "expr": "sum(increase(entnglog_http_upstream_time_seconds_count{job=\"企业业务开发团队\", system=\"xxx系统\", idc=\"$center\",module=\"$module\", upstream=~\"$instance\", request=~\".*$service.*\",status!~\"20\\\\d\"}[10m] offset 7d)) / sum(increase(entnglog_http_upstream_time_seconds_count{job=\"企业业务开发团队\", system=\"xxx系统\", idc=\"$center\",module=\"$module\", upstream=~\"$instance\",request=~\".*$service.*\"}[10m] offset 7d))",
     "legendFormat": "上周"
    }
   ]
  },
  {
   "title": "QPSTop5",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(5, sum(rate(entnglog_http_upstream_time_seconds_count{job=\"企业业务开发团队\", system=\"xxx系统\", idc=\"$center\",module=\"$module\", upstream=~\"$instance\"}[60m])) by (request))",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "耗时Top5",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 7, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum(rate(entnglog_http_upstream_time_seconds_sum{job=\"企业业务开发团队\", system=\"xxx系统\", idc=\"$center\",module=\"$module\", upstream=~\"$instance\"}[60m])) by (request) / sum(rate(entnglog_http_upstream_time_seconds_count{job=\"企业业务开发团队\", system=\"xxx系统\", idc=\"$center\",module=\"$module\", upstream=~\"$instance\"}[60m])) by (request) )",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "错误率Top5",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum(increase(entnglog_http_upstream_time_seconds_count{job=\"企业业务开发团队\", system=\"xxx系统\", idc=\"$center\",module=\"$module\", upstream=~\"$instance\", status!~\"20\\\\d\"}[10m])) by (request) / sum(increase(entnglog_http_upstream_time_seconds_count{job=\"企业业务开发团队\", system=\"xxx系统\", idc=\"$center\",module=\"$module\", upstream=~\"$instance\"}[10m])) by (request))",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "请求P90",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(entnglog_http_upstream_time_seconds_hist_bucket{job=\"企业业务开发团队\", system=\"xxx系统\", idc=\"$center\",module=\"$module\", upstream=~\"$instance\", request=~\".*$service.*\"}[10m])) by (request,le))",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "请求P99",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(entnglog_http_upstream_time_seconds_hist_bucket{job=\"企业业务开发团队\", system=\"xxx系统\", idc=\"$center\",module=\"$module\", upstream=~\"$instance\",request=~\".*$service.*\"}[10m])) by (request,le))",
     "legendFormat": "{{request}}"
    }
   ]
  }
 ]
}